class Time24 {
  //toString,equals and hashCode as generated by eclipse
/*omitted*/
  final int seconds;
  final int minutes;
  final int hours;
  Time24(int seconds, int minutes, int hours){
    this.seconds=limit60(seconds);
    this.minutes = limit60(minutes);
    this.hours=limitHours(hours);
  }
  private static int limit60(int v){// 0..59 ok
    if(v<0|| v>59){throw new IllegalArgumentException("limit60 over "+v);}
    return v;
  }
  private static int limitHours(int v){//0..23 ok
    if(v<0|| v>23){throw new IllegalArgumentException("limitHours over "+v);}
    return v;
  }
  static final Time24 twelve= new Time24(0,0,12);
  
  
  public Time24 add1Hour() {
		
		return new Time24(seconds,minutes,limitHours(hours));
	}
  public Time24 remove1Hour(){
               return new Time24(seconds,minutes,24-limitHours(hours));
}

public Time24 add1Minute(){
              if(minutes==1440){return twelve;}
              return new Time24(seconds,limit60(minutes%60),limitHours(minutes/60));
}

public Time24 remove1Minute(){
             return new Time24(seconds,60-limit60(minutes%60),limitHours(hours-minutes/60));
}


 
  
}

public class time1{
  public static void checkAdd(Time24 t){
    Time24 test=t;
    for(int i=0;i<24;i++){test=test.add1Hour();}
    assert test.equals(t):
    "if I add 24 hours, is the same as before for:"+t;
  }
  public static void main(String[]arg){
    checkAdd(Time24.twelve);
    checkAdd(new Time24(10,10,10));
    checkAdd(new Time24(59,59,23));
  }
}